import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { RootState, AppThunk } from '../../app/store'
import getStudentsFromClass from './services/studentServices' 

const GET_STUDENT = 'mini-extension/student/GET_STUDENT'
// const LOGOUT = 'mini-extension/student/LOGOUT'

export type RecordState = {
	records: any[]
}

const initialState: RecordState = {
	records: [],
}

export const incrementAsync = createAsyncThunk(GET_STUDENT, async (name: string) => {
	const result = await getStudentsFromClass(name)
	return result
})

export const airtableSlice = createSlice({
	name: 'records',
	initialState,
	
	reducers: {
		getStudent: (state, action: PayloadAction<[]>) => {
			const { payload } = action
			state.records = [...state.records, ...payload]
		},
		logout: (state) => {
			state.records = []
		}
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: builder => {
		builder
			.addCase(incrementAsync.pending, state => {
				state.status = 'loading'
			})
			.addCase(incrementAsync.fulfilled, (state, action) => {
				state.status = 'idle'
				state.value += action.payload
			})
			.addCase(incrementAsync.rejected, state => {
				state.status = 'failed'
			})
	},
})

export const { getStudent, logout } = airtableSlice.actions

export const recordList = (state: RootState) => state.records

export default airtableSlice.reducer
